elasticsearch:
  extends:
    file: docker-compose-common.yml
    service: elasticsearch
  image: elasticsearch
logstash:
  extends:
    file: docker-compose-common.yml
    service: logstash
  image: logstash
  links:
    - elasticsearch:elasticsearch
kibana:
  extends:
    file: docker-compose-common.yml
    service: kibana
  image: kibana
logspout:
  net: container:logstash
  extends:
    file: docker-compose-common.yml
    service: logspout
  image: gliderlabs/logspout
cadvisor:
  extends:
    file: docker-compose-common.yml
    service: cadvisor
